config/routes.rb
Rails.application.routes.draw do
  root 'chores#index'
  resources :chores do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chore.rb
class Chore < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :chore
  validates :body, presence: true
  validates :commenter, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern
  VALID_STATUSES = %w[public private archived].freeze
  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  def index
    @chores = Chore.all
  end

  def show
    @chore = Chore.find(params[:id])
  end

  def new
    @chore = Chore.new
  end

  def create
    @chore = Chore.new(chore_params)
    if @chore.save
      redirect_to @chore
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @chore = Chore.find(params[:id])
  end

  def update
    @chore = Chore.find(params[:id])
    if @chore.update(chore_params)
      redirect_to @chore
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy
    redirect_to chores_path, status: :see_other
  end

  private

  def chore_params
    params.require(:chore).permit(:title, :description, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @chore = chore.find(params[:chore_id])
    @comment = @chore.comments.create(comment_params)
    redirect_to chore_path(@chore)
  end

  def destroy
    @chore = chore.find(params[:chore_id])
    @comment = @chore.comments.find(params[:id])
    @comment.destroy
    redirect_to chore_path(@chore), :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/chores/_form.html.erb
<%= form_with class:'space-y-4', model: chore do |form| %>
  <div>
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
    <% chore.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :description, class: 'label' %>
    <%= form.text_area :description, class: 'input' %>
    <% chore.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :status, class:'label' %>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
  <%= form.submit 'submit', class:'btn -primary' %>
  <% if chore.errors.full_messages.length > 0 %>
    <div class="bg-red-100 text-red-900 p-3 rounded-lg mt-3">
      <ul class="list-disc list-inside">
        <% chore.errors.full_messages.each do |message| %>
          <li class="">
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/chores/edit.html.erb
<h1> Edit Chore <%= link_to "Destroy", chore_path(@chore), data: {
    turbo_method: "delete",
    turbo_confirm: "Are you sure?"
}, class: 'btn -danger' %></h1>
<div>
  <%= render "form", chore:@chore %>
</div>

app/views/chores/index.html.erb
<h1>Current Chores</h1>
<i>there are <%= Chore.public_count %> chore(s) to do</i>
<ul>
  <% @chores.each do |chore| %>
    <% unless chore.archived? %>
      <li><%= link_to chore.title,chore %> <%= link_to 'edit',edit_chore_path(chore), class: "link" %> </li>
      <p class="text-xs">
        <% if chore.comments.public_count > 0 %>
          <%= chore.comments.public_count %>
        <% end %>
      </p>
    <% end %>
  <% end %>
</ul>
<div>
  <%= link_to 'New Chore',new_chore_path, class: "btn -primary" %>
</div>

app/views/chores/new.html.erb
<h1> New Chore</h1>
<%= render "form", chore:@chore %>

app/views/chores/show.html.erb
<%= link_to "Edit",edit_chore_path(@chore), class: 'btn' %>
<%= link_to "Destroy", chore_path(@chore), data: { turbo_method: "delete",
    turbo_confirm: "Are you sure?" }, class: 'btn -danger' %>
<h1><%= @chore.title %></h1>
<p><%= @chore.description %></p>
<h2>
  Leave a comment:
</h2>
<%= render 'comments/form' %>
<h3>Comments</h3>
<%= render @chore.comments %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <%= link_to "Remove Comment",[comment.chore, comment], data: { turbo_method: "delete" }, class: 'link text-sm' %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [@chore, @chore.comments.build] do |form| %>
  <p>
    <div>
      <%= form.label :commenter, class: 'label' %>
      <%= form.text_field :commenter, class: 'input' %>
    </div>
  </p>
  <div>
    <%= form.label :body, class: 'label' %>
    <%= form.text_area :body, class: 'input' %>
    <%= form.label :status, class: 'label' %>
    <%= form.select :status, %w[public private archived], selected: 'public', class:'public' %>
    <%= form.submit "Submit", class: 'btn' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chores</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <div>
        <%= link_to 'Home', root_path, class: 'link' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>